//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace ProgressUIPrototype
{
    sealed class LegoLoader : IAnimatedVisualSource
    {
        public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            if (!IsRuntimeCompatible())
            {
                return null;
            }
            return new AnimatedVisual(compositor);
        }

        static bool IsRuntimeCompatible()
        {
            if (!Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.UI.Composition.CompositionGeometricClip"))
            {
                return false;
            }
            return true;
        }

        sealed class AnimatedVisual : IAnimatedVisual
        {
            const long c_durationTicks = 20000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _colorBrush_AlmostCrimson_FFD3001D;
            CompositionColorBrush _colorBrush_AlmostCrimson_FFE6242A;
            CompositionColorBrush _colorBrush_AlmostDarkOrange_FFFD6914;
            CompositionColorBrush _colorBrush_AlmostGoldenrod_FFE7B825;
            CompositionColorBrush _colorBrush_AlmostOliveDrab_FF719318;
            CompositionColorBrush _colorBrush_AlmostOrangeRed_FFF45205;
            CompositionColorBrush _colorBrush_AlmostSandyBrown_FFFF9D52;
            CompositionColorBrush _colorBrush_AlmostSteelBlue_FF2585A9;
            CompositionColorBrush _colorBrush_AlmostTomato_FFEB413B;
            CompositionColorBrush _colorBrush_AlmostYellowGreen_FF96C42F;
            CompositionColorBrush _colorBrush_AlmostYellowGreen_FF9ED027;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            StepEasingFunction _holdThenStepEasingFunction;
            CompositionPathGeometry _pathGeometry_00;
            CompositionPathGeometry _pathGeometry_01;
            CompositionPathGeometry _pathGeometry_02;
            CompositionPathGeometry _pathGeometry_03;
            CompositionPathGeometry _pathGeometry_04;
            CompositionPathGeometry _pathGeometry_09;
            CompositionPathGeometry _pathGeometry_12;
            CompositionPathGeometry _pathGeometry_13;
            ContainerVisual _root;
            ExpressionAnimation _scalarExpressionAnimation;
            StepEasingFunction _stepThenHoldEasingFunction;
            ScalarKeyFrameAnimation _transformMatrix_11ScalarAnimation_to_0_0;
            ScalarKeyFrameAnimation _transformMatrix_11ScalarAnimation_to_1_0;

            CompositionColorBrush ColorBrush_AlmostCrimson_FFD3001D()
            {
                return _colorBrush_AlmostCrimson_FFD3001D = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xD3, 0x00, 0x1D));
            }

            CompositionColorBrush ColorBrush_AlmostCrimson_FFE6242A()
            {
                return _colorBrush_AlmostCrimson_FFE6242A = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xE6, 0x24, 0x2A));
            }

            CompositionColorBrush ColorBrush_AlmostDarkOrange_FFFD6914()
            {
                return _colorBrush_AlmostDarkOrange_FFFD6914 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFD, 0x69, 0x14));
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionColorBrush ColorBrush_AlmostGold_FFF9E22E()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF9, 0xE2, 0x2E));
            }

            CompositionColorBrush ColorBrush_AlmostGoldenrod_FFE7B825()
            {
                return _colorBrush_AlmostGoldenrod_FFE7B825 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xE7, 0xB8, 0x25));
            }

            // Layer (Shape): blue
            // Path 1
            CompositionColorBrush ColorBrush_AlmostLightSkyBlue_FF63D2F3()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x63, 0xD2, 0xF3));
            }

            // Layer (Shape): blue
            // Path 1
            CompositionColorBrush ColorBrush_AlmostMediumTurquoise_FF4FACCE()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x4F, 0xAC, 0xCE));
            }

            CompositionColorBrush ColorBrush_AlmostOliveDrab_FF719318()
            {
                return _colorBrush_AlmostOliveDrab_FF719318 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x71, 0x93, 0x18));
            }

            CompositionColorBrush ColorBrush_AlmostOrangeRed_FFF45205()
            {
                return _colorBrush_AlmostOrangeRed_FFF45205 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF4, 0x52, 0x05));
            }

            CompositionColorBrush ColorBrush_AlmostSandyBrown_FFFF9D52()
            {
                return _colorBrush_AlmostSandyBrown_FFFF9D52 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0x9D, 0x52));
            }

            CompositionColorBrush ColorBrush_AlmostSteelBlue_FF2585A9()
            {
                return _colorBrush_AlmostSteelBlue_FF2585A9 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x25, 0x85, 0xA9));
            }

            CompositionColorBrush ColorBrush_AlmostTomato_FFEB413B()
            {
                return _colorBrush_AlmostTomato_FFEB413B = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0x41, 0x3B));
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionColorBrush ColorBrush_AlmostYellow_FFF9EB2F()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF9, 0xEB, 0x2F));
            }

            CompositionColorBrush ColorBrush_AlmostYellowGreen_FF96C42F()
            {
                return _colorBrush_AlmostYellowGreen_FF96C42F = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x96, 0xC4, 0x2F));
            }

            CompositionColorBrush ColorBrush_AlmostYellowGreen_FF9ED027()
            {
                return _colorBrush_AlmostYellowGreen_FF9ED027 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x9E, 0xD0, 0x27));
            }

            // Layer (Shape): orange 2
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(0, 0, 0, 0, 0, 0);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_01());
                result.StartAnimation("TransformMatrix._11", TransformMatrix_11ScalarAnimation_to_1_0());
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(314.649994F, 300.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_00());
                shapes.Add(SpriteShape_01());
                shapes.Add(SpriteShape_02());
                shapes.Add(SpriteShape_03());
                shapes.Add(SpriteShape_04());
                shapes.Add(SpriteShape_05());
                shapes.Add(SpriteShape_06());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 306.474),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_0());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", ScalarExpressionAnimation());
                return result;
            }

            // Layer (Shape): red 2
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(0, 0, 0, 0, 0, 0);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_03());
                result.StartAnimation("TransformMatrix._11", _transformMatrix_11ScalarAnimation_to_1_0);
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(371.75F, 340.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_07());
                shapes.Add(SpriteShape_08());
                shapes.Add(SpriteShape_09());
                shapes.Add(SpriteShape_10());
                shapes.Add(SpriteShape_11());
                shapes.Add(SpriteShape_12());
                shapes.Add(SpriteShape_13());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 193.074),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_1());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): yellow
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(371.549988F, 260.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_14());
                shapes.Add(SpriteShape_15());
                shapes.Add(SpriteShape_16());
                shapes.Add(SpriteShape_17());
                shapes.Add(SpriteShape_18());
                shapes.Add(SpriteShape_19());
                shapes.Add(SpriteShape_20());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 419.874),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_2());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): orange
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_06());
                result.StartAnimation("TransformMatrix._11", TransformMatrix_11ScalarAnimation_to_0_0());
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(314.649994F, 300.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_21());
                shapes.Add(SpriteShape_22());
                shapes.Add(SpriteShape_23());
                shapes.Add(SpriteShape_24());
                shapes.Add(SpriteShape_25());
                shapes.Add(SpriteShape_26());
                shapes.Add(SpriteShape_27());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 306.474),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_3());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): blue
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(485.350006F, 259.875F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_28());
                shapes.Add(SpriteShape_29());
                shapes.Add(SpriteShape_30());
                shapes.Add(SpriteShape_31());
                shapes.Add(SpriteShape_32());
                shapes.Add(SpriteShape_33());
                shapes.Add(SpriteShape_34());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 646.674),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_4());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): green
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_09());
                result.StartAnimation("TransformMatrix._11", TransformMatrix_11ScalarAnimation_to_0_1());
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(428.950012F, 300.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_35());
                shapes.Add(SpriteShape_36());
                shapes.Add(SpriteShape_37());
                shapes.Add(SpriteShape_38());
                shapes.Add(SpriteShape_39());
                shapes.Add(SpriteShape_40());
                shapes.Add(SpriteShape_41());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 533.273),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_5());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): red
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_11());
                result.StartAnimation("TransformMatrix._11", _transformMatrix_11ScalarAnimation_to_0_0);
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            CompositionContainerShape ContainerShape_11()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(371.75F, 340.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_42());
                shapes.Add(SpriteShape_43());
                shapes.Add(SpriteShape_44());
                shapes.Add(SpriteShape_45());
                shapes.Add(SpriteShape_46());
                shapes.Add(SpriteShape_47());
                shapes.Add(SpriteShape_48());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 193.074),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_6());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): green 2
            CompositionContainerShape ContainerShape_12()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(0, 0, 0, 0, 0, 0);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_13());
                result.StartAnimation("TransformMatrix._11", TransformMatrix_11ScalarAnimation_to_1_1());
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            CompositionContainerShape ContainerShape_13()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(428.950012F, 300.125F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_49());
                shapes.Add(SpriteShape_50());
                shapes.Add(SpriteShape_51());
                shapes.Add(SpriteShape_52());
                shapes.Add(SpriteShape_53());
                shapes.Add(SpriteShape_54());
                shapes.Add(SpriteShape_55());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 533.273),(my.Position.Y - 300))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_7());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "_.Progress * 0.8388897";
                _reusableExpressionAnimation.SetReferenceParameter("_", _root);
                controller.StartAnimation("Progress", _reusableExpressionAnimation);
                return result;
            }

            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip();
                result.Size = new Vector2(800, 600);
                var children = result.Children;
                children.InsertAtTop(ShapeVisual());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.560000002F, 0), new Vector2(0.439999998F, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.560000002F, 0.560000002F), new Vector2(0.439999998F, 0.439999998F));
            }

            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(28.3500004F, -40.1399994F));
                    builder.AddLine(new Vector2(28.3500004F, 0));
                    builder.AddLine(new Vector2(-28.3500004F, 40.1399994F));
                    builder.AddLine(new Vector2(-28.3500004F, 0));
                    builder.AddLine(new Vector2(28.3500004F, -40.1399994F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(56.7000008F, -0.00999999978F));
                    builder.AddLine(new Vector2(0, 40.1300011F));
                    builder.AddLine(new Vector2(-56.7000008F, -0.00999999978F));
                    builder.AddLine(new Vector2(0, -40.1300011F));
                    builder.AddLine(new Vector2(56.7000008F, -0.00999999978F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(28.3500004F, -0.00100000005F));
                    builder.AddLine(new Vector2(28.3500004F, 40.1409988F));
                    builder.AddLine(new Vector2(-28.3500004F, -0.00100000005F));
                    builder.AddLine(new Vector2(-28.3500004F, -40.1409988F));
                    builder.AddLine(new Vector2(28.3500004F, -0.00100000005F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8500004F, -6.33099985F));
                    builder.AddLine(new Vector2(11.9099998F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9099998F, 3.28999996F), new Vector2(6.57000017F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.57000017F, 7.23000002F), new Vector2(-11.9099998F, 3.28999996F), new Vector2(-11.9099998F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9099998F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9099998F, -2.36999989F), new Vector2(-6.57000017F, 1.54900002F), new Vector2(-0.00999999978F, 1.54900002F));
                    builder.AddCubicBezier(new Vector2(6.1500001F, 1.54900002F), new Vector2(11.2299995F, -1.89100003F), new Vector2(11.8500004F, -6.33099985F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8500004F, -6.32999992F));
                    builder.AddLine(new Vector2(11.9099998F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9099998F, 3.28999996F), new Vector2(6.57000017F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.57000017F, 7.23000002F), new Vector2(-11.9099998F, 3.28999996F), new Vector2(-11.9099998F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9099998F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9099998F, -2.36999989F), new Vector2(-6.57000017F, 1.54999995F), new Vector2(-0.00999999978F, 1.54999995F));
                    builder.AddCubicBezier(new Vector2(6.1500001F, 1.54999995F), new Vector2(11.2299995F, -1.88999999F), new Vector2(11.8500004F, -6.32999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(28.3500004F, -40.1399994F));
                    builder.AddLine(new Vector2(28.3500004F, 0));
                    builder.AddLine(new Vector2(-28.3490009F, 40.1399994F));
                    builder.AddLine(new Vector2(-28.3490009F, 0));
                    builder.AddLine(new Vector2(28.3500004F, -40.1399994F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(56.6990013F, -0.00999999978F));
                    builder.AddLine(new Vector2(0, 40.1300011F));
                    builder.AddLine(new Vector2(-56.7000008F, -0.00999999978F));
                    builder.AddLine(new Vector2(0, -40.1300011F));
                    builder.AddLine(new Vector2(56.6990013F, -0.00999999978F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8509998F, -6.33099985F));
                    builder.AddLine(new Vector2(11.9110003F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9110003F, 3.28999996F), new Vector2(6.5710001F, 7.23000002F), new Vector2(-0.00899999961F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.56899977F, 7.23000002F), new Vector2(-11.9099998F, 3.28999996F), new Vector2(-11.9099998F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9099998F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9099998F, -2.36999989F), new Vector2(-6.56899977F, 1.54900002F), new Vector2(-0.00899999961F, 1.54900002F));
                    builder.AddCubicBezier(new Vector2(6.15100002F, 1.54900002F), new Vector2(11.2309999F, -1.89100003F), new Vector2(11.8509998F, -6.33099985F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8500004F, -6.32999992F));
                    builder.AddLine(new Vector2(11.9099998F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9099998F, 3.28999996F), new Vector2(6.57000017F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.5710001F, 7.23000002F), new Vector2(-11.9110003F, 3.28999996F), new Vector2(-11.9110003F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9110003F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9110003F, -2.36999989F), new Vector2(-6.5710001F, 1.54999995F), new Vector2(-0.00999999978F, 1.54999995F));
                    builder.AddCubicBezier(new Vector2(6.1500001F, 1.54999995F), new Vector2(11.2299995F, -1.88999999F), new Vector2(11.8500004F, -6.32999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8509998F, -6.32999992F));
                    builder.AddLine(new Vector2(11.9110003F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9110003F, 3.28999996F), new Vector2(6.57000017F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.57000017F, 7.23000002F), new Vector2(-11.9110003F, 3.28999996F), new Vector2(-11.9110003F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9110003F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9110003F, -2.36999989F), new Vector2(-6.57000017F, 1.54999995F), new Vector2(-0.00999999978F, 1.54999995F));
                    builder.AddCubicBezier(new Vector2(6.1500001F, 1.54999995F), new Vector2(11.2309999F, -1.88999999F), new Vector2(11.8509998F, -6.32999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.849F, -6.32999992F));
                    builder.AddLine(new Vector2(11.9099998F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9099998F, 3.28999996F), new Vector2(6.57000017F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.5710001F, 7.23000002F), new Vector2(-11.9110003F, 3.28999996F), new Vector2(-11.9110003F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9110003F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9110003F, -2.36999989F), new Vector2(-6.5710001F, 1.54999995F), new Vector2(-0.00999999978F, 1.54999995F));
                    builder.AddCubicBezier(new Vector2(6.1500001F, 1.54999995F), new Vector2(11.2290001F, -1.88999999F), new Vector2(11.849F, -6.32999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8500004F, -6.32999992F));
                    builder.AddLine(new Vector2(11.9110003F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9110003F, 3.28999996F), new Vector2(6.5710001F, 7.23000002F), new Vector2(-0.00899999961F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.57000017F, 7.23000002F), new Vector2(-11.9099998F, 3.28999996F), new Vector2(-11.9099998F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9099998F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9099998F, -2.36999989F), new Vector2(-6.57000017F, 1.54999995F), new Vector2(-0.00899999961F, 1.54999995F));
                    builder.AddCubicBezier(new Vector2(6.15100002F, 1.54999995F), new Vector2(11.2309999F, -1.88999999F), new Vector2(11.8500004F, -6.32999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.849F, -6.33099985F));
                    builder.AddLine(new Vector2(11.9099998F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9099998F, 3.28999996F), new Vector2(6.56899977F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.5710001F, 7.23000002F), new Vector2(-11.9110003F, 3.28999996F), new Vector2(-11.9110003F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9110003F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9110003F, -2.36999989F), new Vector2(-6.5710001F, 1.54900002F), new Vector2(-0.00999999978F, 1.54900002F));
                    builder.AddCubicBezier(new Vector2(6.14900017F, 1.54900002F), new Vector2(11.2290001F, -1.89100003F), new Vector2(11.849F, -6.33099985F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(11.8500004F, -6.32999992F));
                    builder.AddLine(new Vector2(11.9110003F, -1.57000005F));
                    builder.AddCubicBezier(new Vector2(11.9110003F, 3.28999996F), new Vector2(6.57000017F, 7.23000002F), new Vector2(-0.00999999978F, 7.23000002F));
                    builder.AddCubicBezier(new Vector2(-6.57000017F, 7.23000002F), new Vector2(-11.9099998F, 3.28999996F), new Vector2(-11.9099998F, -1.57000005F));
                    builder.AddLine(new Vector2(-11.9099998F, -7.23000002F));
                    builder.AddCubicBezier(new Vector2(-11.9099998F, -2.36999989F), new Vector2(-6.57000017F, 1.54999995F), new Vector2(-0.00999999978F, 1.54999995F));
                    builder.AddCubicBezier(new Vector2(6.1500001F, 1.54999995F), new Vector2(11.2299995F, -1.88999999F), new Vector2(11.8500004F, -6.32999992F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame  = true;
                return result;
            }

            InsetClip InsetClip()
            {
                var result = _c.CreateInsetClip();
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_00()
            {
                var result = _pathGeometry_00 = _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_01()
            {
                var result = _pathGeometry_01 = _c.CreatePathGeometry(new CompositionPath(Geometry_01()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_02()
            {
                var result = _pathGeometry_02 = _c.CreatePathGeometry(new CompositionPath(Geometry_02()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_03()
            {
                var result = _pathGeometry_03 = _c.CreatePathGeometry(new CompositionPath(Geometry_03()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_04()
            {
                var result = _pathGeometry_04 = _c.CreatePathGeometry(new CompositionPath(Geometry_04()));
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_05()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_05()));
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_06()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_06()));
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_07()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_07()));
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_08()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_08()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_09()
            {
                var result = _pathGeometry_09 = _c.CreatePathGeometry(new CompositionPath(Geometry_09()));
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_10()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_10()));
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_11()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_11()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_12()
            {
                var result = _pathGeometry_12 = _c.CreatePathGeometry(new CompositionPath(Geometry_12()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_13()
            {
                var result = _pathGeometry_13 = _c.CreatePathGeometry(new CompositionPath(Geometry_13()));
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_0()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(314.649994F, 300.125F), HoldThenStepEasingFunction());
                result.InsertKeyFrame(0.19867529F, new Vector2(371.350006F, 259.725006F), CubicBezierEasingFunction_0());
                result.InsertKeyFrame(0.794701159F, new Vector2(371.350006F, 259.725006F), CubicBezierEasingFunction_1());
                result.InsertKeyFrame(0.993376493F, new Vector2(428.049988F, 219.585007F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_1()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(371.75F, 340.125F), StepThenHoldEasingFunction());
                result.InsertKeyFrame(0.19867529F, new Vector2(371.75F, 340.125F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.39735058F, new Vector2(315.049988F, 299.984985F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.86092627F, new Vector2(315.049988F, 299.984985F), _cubicBezierEasingFunction_1);
                result.InsertKeyFrame(0.993376493F, new Vector2(371.75F, 259.845001F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_2()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(371.549988F, 260.125F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.19867529F, new Vector2(428.25F, 219.725006F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.596025884F, new Vector2(428.25F, 219.725006F), _cubicBezierEasingFunction_1);
                result.InsertKeyFrame(0.794701159F, new Vector2(484.950012F, 259.86499F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_3()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(314.649994F, 300.125F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0662250966F, new Vector2(314.649994F, 300.125F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.19867529F, new Vector2(371.350006F, 259.725006F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.794701159F, new Vector2(371.350006F, 259.725006F), _cubicBezierEasingFunction_1);
                result.InsertKeyFrame(0.993377507F, new Vector2(428.049988F, 219.585007F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_4()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(485.350006F, 259.875F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.463575691F, new Vector2(485.350006F, 259.875F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.596025884F, new Vector2(428.649994F, 300.015015F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_5()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(428.950012F, 300.125F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.39735058F, new Vector2(428.950012F, 300.125F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.59602648F, new Vector2(372.25F, 340.265015F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_6()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(371.75F, 340.125F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.19867529F, new Vector2(371.75F, 340.125F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.39735058F, new Vector2(315.049988F, 299.984985F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.794701159F, new Vector2(315.049988F, 299.984985F), _cubicBezierEasingFunction_1);
                result.InsertKeyFrame(0.993377507F, new Vector2(371.75F, 259.845001F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_7()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(428.950012F, 300.125F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.333333343F, new Vector2(428.950012F, 300.125F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(372.25F, 340.265015F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.833333313F, new Vector2(372.25F, 340.265015F), _cubicBezierEasingFunction_1);
                result.InsertKeyFrame(1, new Vector2(315.549988F, 299.86499F), _cubicBezierEasingFunction_0);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0);
                var children = result.Children;
                children.InsertAtTop(ContainerVisual_1());
                return result;
            }

            ExpressionAnimation ScalarExpressionAnimation()
            {
                var result = _scalarExpressionAnimation = _c.CreateExpressionAnimation();
                result.SetReferenceParameter("_", _root);
                result.Expression = "_.Progress";
                return result;
            }

            ShapeVisual ShapeVisual()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(800, 600);
                var shapes = result.Shapes;
                // Layer (Shape): orange 2
                shapes.Add(ContainerShape_00());
                // Layer (Shape): red 2
                shapes.Add(ContainerShape_02());
                // Layer (Shape): yellow
                shapes.Add(ContainerShape_04());
                // Layer (Shape): orange
                shapes.Add(ContainerShape_05());
                // Layer (Shape): blue
                shapes.Add(ContainerShape_07());
                // Layer (Shape): green
                shapes.Add(ContainerShape_08());
                // Layer (Shape): red
                shapes.Add(ContainerShape_10());
                // Layer (Shape): green 2
                shapes.Add(ContainerShape_12());
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 334.824005F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostOrangeRed_FFF45205();
                result.Geometry = PathGeometry_00();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 306.473999F, 279.929993F);
                result.FillBrush = ColorBrush_AlmostSandyBrown_FFFF9D52();
                result.Geometry = PathGeometry_01();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 278.123993F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFFD6914();
                result.Geometry = PathGeometry_02();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 307.70401F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = PathGeometry_03();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 334.26001F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = PathGeometry_04();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 307.25F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 280.692993F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 221.423996F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostCrimson_FFD3001D();
                result.Geometry = _pathGeometry_00;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 193.074005F, 279.929993F);
                result.FillBrush = ColorBrush_AlmostTomato_FFEB413B();
                result.Geometry = _pathGeometry_01;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 164.723999F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostCrimson_FFE6242A();
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 194.304001F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_03;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 220.860001F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_12()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 193.850006F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_13()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 167.294006F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_14()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 448.223999F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostGoldenrod_FFE7B825();
                result.Geometry = PathGeometry_05();
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_15()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 419.873993F, 279.929993F);
                result.FillBrush = ColorBrush_AlmostYellow_FFF9EB2F();
                result.Geometry = PathGeometry_06();
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_16()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 391.523987F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostGold_FFF9E22E();
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_17()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 421.104004F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostGoldenrod_FFE7B825;
                result.Geometry = PathGeometry_07();
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_18()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 447.660004F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostGoldenrod_FFE7B825;
                result.Geometry = PathGeometry_08();
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_19()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 420.649994F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostGoldenrod_FFE7B825;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Layer (Shape): yellow
            // Path 1
            CompositionSpriteShape SpriteShape_20()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 394.093994F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostGoldenrod_FFE7B825;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_21()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 334.824005F, 320.059998F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_00;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_22()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 306.473999F, 279.929993F);
                result.FillBrush = _colorBrush_AlmostSandyBrown_FFFF9D52;
                result.Geometry = _pathGeometry_01;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_23()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 278.123993F, 320.059998F);
                result.FillBrush = _colorBrush_AlmostDarkOrange_FFFD6914;
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_24()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 307.70401F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_03;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_25()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 334.26001F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_26()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 307.25F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_27()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 280.692993F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOrangeRed_FFF45205;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_28()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 675.023987F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostSteelBlue_FF2585A9();
                result.Geometry = _pathGeometry_00;
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_29()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 646.674011F, 279.929993F);
                result.FillBrush = ColorBrush_AlmostLightSkyBlue_FF63D2F3();
                result.Geometry = _pathGeometry_01;
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_30()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 618.323975F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostMediumTurquoise_FF4FACCE();
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_31()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 647.903992F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostSteelBlue_FF2585A9;
                result.Geometry = _pathGeometry_03;
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_32()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 674.460022F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostSteelBlue_FF2585A9;
                result.Geometry = PathGeometry_09();
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_33()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 647.450012F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostSteelBlue_FF2585A9;
                result.Geometry = PathGeometry_10();
                return result;
            }

            // Layer (Shape): blue
            // Path 1
            CompositionSpriteShape SpriteShape_34()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 620.893982F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostSteelBlue_FF2585A9;
                result.Geometry = PathGeometry_11();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_35()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 561.624023F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostOliveDrab_FF719318();
                result.Geometry = _pathGeometry_00;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_36()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 533.273987F, 279.929993F);
                result.FillBrush = ColorBrush_AlmostYellowGreen_FF9ED027();
                result.Geometry = _pathGeometry_01;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_37()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 504.923004F, 320.059998F);
                result.FillBrush = ColorBrush_AlmostYellowGreen_FF96C42F();
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_38()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 534.504028F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = PathGeometry_12();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_39()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 561.060974F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = PathGeometry_13();
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_40()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 534.049988F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_09;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_41()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 507.493988F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_42()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 221.423996F, 320.059998F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_00;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_43()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 193.074005F, 279.929993F);
                result.FillBrush = _colorBrush_AlmostTomato_FFEB413B;
                result.Geometry = _pathGeometry_01;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_44()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 164.723999F, 320.059998F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFE6242A;
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_45()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 194.304001F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_03;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_46()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 220.860001F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_47()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 193.850006F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_48()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 167.294006F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostCrimson_FFD3001D;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_49()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 561.624023F, 320.059998F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_00;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_50()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 533.273987F, 279.929993F);
                result.FillBrush = _colorBrush_AlmostYellowGreen_FF9ED027;
                result.Geometry = _pathGeometry_01;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_51()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 504.923004F, 320.059998F);
                result.FillBrush = _colorBrush_AlmostYellowGreen_FF96C42F;
                result.Geometry = _pathGeometry_02;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_52()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 534.504028F, 302.130005F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_12;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_53()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 561.060974F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_13;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_54()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 534.049988F, 262.515015F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_09;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_55()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 507.493988F, 282.322998F);
                result.FillBrush = _colorBrush_AlmostOliveDrab_FF719318;
                result.Geometry = _pathGeometry_04;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame  = true;
                return result;
            }

            ScalarKeyFrameAnimation TransformMatrix_11ScalarAnimation_to_0_0()
            {
                var result = _transformMatrix_11ScalarAnimation_to_0_0 = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.794701993F, 0, _holdThenStepEasingFunction);
                return result;
            }

            // Layer (Shape): green
            ScalarKeyFrameAnimation TransformMatrix_11ScalarAnimation_to_0_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.397350997F, 0, _holdThenStepEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation TransformMatrix_11ScalarAnimation_to_1_0()
            {
                var result = _transformMatrix_11ScalarAnimation_to_1_0 = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.794701993F, 1, _holdThenStepEasingFunction);
                return result;
            }

            // Layer (Shape): green 2
            ScalarKeyFrameAnimation TransformMatrix_11ScalarAnimation_to_1_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.397350997F, 1, _holdThenStepEasingFunction);
                return result;
            }

            internal AnimatedVisual(Compositor compositor)
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            Visual IAnimatedVisual.RootVisual => _root;
            TimeSpan IAnimatedVisual.Duration => TimeSpan.FromTicks(c_durationTicks);
            Vector2 IAnimatedVisual.Size => new Vector2(800, 600);
            void IDisposable.Dispose() => _root?.Dispose();
        }
    }
}
